# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180304_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='libraryCard',
        ),
    ]
