# Generated by Django 2.0.2 on 2018-02-06 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField()),
                ('until', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('release', models.DateField()),
                ('edition', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('thumbnailUrl', models.CharField(max_length=150)),
                ('numberOfCopies', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Document')),
                ('isbn', models.CharField(max_length=50)),
            ],
            bases=('catalog.document',),
        ),
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Document')),
                ('journal', models.CharField(max_length=50)),
            ],
            bases=('catalog.document',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Document')),
                ('videoUrl', models.CharField(max_length=150)),
            ],
            bases=('catalog.document',),
        ),
        migrations.AddField(
            model_name='checkout',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Document'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
