# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='until',
            field=models.DateField(default=datetime.datetime(2018, 3, 25, 8, 28, 28, 136784)),
        ),
    ]
