# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 14:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180304_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Document')),
            ],
        ),
        migrations.AlterField(
            model_name='checkout',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Document'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='until',
            field=models.DateField(default=datetime.datetime(2018, 3, 25, 14, 57, 55, 874249)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
