# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 16:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180304_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='copies_count',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='until',
            field=models.DateField(default=datetime.datetime(2018, 3, 25, 16, 28, 55, 277573)),
        ),
    ]
