# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180304_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='until',
            field=models.DateField(default=datetime.datetime(2018, 3, 25, 16, 38, 36, 130534)),
        ),
        migrations.AlterField(
            model_name='copy',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Document'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Document'),
        ),
    ]
